name: Eventasaurus
options:
  bundleIdPrefix: com.wombie
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig

packages:
  Clerk:
    url: https://github.com/clerk/clerk-ios
    from: "1.0.0"

targets:
  Eventasaurus:
    type: application
    platform: iOS
    sources:
      - path: Eventasaurus
    info:
      path: Eventasaurus/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocationWhenInUseUsageDescription: "Wombie uses your location to find events near you."
        APIBaseURL: $(API_BASE_URL)
        APIBaseURLProd: $(API_BASE_URL_PROD)
        ClerkPublishableKey: $(CLERK_PUBLISHABLE_KEY)
        ClerkPublishableKeyProd: $(CLERK_PUBLISHABLE_KEY_PROD)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wombie.app
        DEVELOPMENT_TEAM: SG49J63DUY
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"Eventasaurus/Preview Content\""
    dependencies:
      - package: Clerk
        product: ClerkKit
      - package: Clerk
        product: ClerkKitUI

  EventasaurusTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: EventasaurusTests
    dependencies:
      - target: Eventasaurus
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Eventasaurus.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Eventasaurus"
