name: Eventasaurus
options:
  bundleIdPrefix: com.eventasaurus
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  Clerk:
    url: https://github.com/clerk/clerk-ios
    from: "1.0.0"

targets:
  Eventasaurus:
    type: application
    platform: iOS
    sources:
      - path: Eventasaurus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.eventasaurus.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"Eventasaurus/Preview Content\""
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Eventasaurus uses your location to find events near you."
    dependencies:
      - package: Clerk
        product: ClerkKit
      - package: Clerk
        product: ClerkKitUI

  EventasaurusTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: EventasaurusTests
    dependencies:
      - target: Eventasaurus
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Eventasaurus.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Eventasaurus"
