# Cross-classification mappings for multi-category support
# These mappings are for the secondary categories generated by the extraction logic
# in CategoryExtractor's cross-classification functions

alias EventasaurusApp.Repo
alias EventasaurusDiscovery.Categories.{Category, CategoryMapping}
import Ecto.Query

IO.puts("🔄 Seeding cross-classification mappings...")

# Get all categories for mapping
categories = Repo.all(Category) |> Enum.map(&{&1.name, &1}) |> Map.new()

# Helper function to insert mapping if it doesn't exist
insert_mapping = fn mapping ->
  category = Map.get(categories, mapping.category_name)

  if category do
    existing = Repo.one(
      from cm in CategoryMapping,
      where: cm.external_source == ^mapping.source,
      where: is_nil(cm.external_type),
      where: fragment("LOWER(?) = LOWER(?)", cm.external_value, ^mapping.value)
    )

    unless existing do
      %CategoryMapping{}
      |> CategoryMapping.changeset(%{
        external_source: mapping.source,
        external_type: mapping.type,
        external_value: mapping.value,
        category_id: category.id,
        priority: mapping.priority,
        external_locale: mapping.locale
      })
      |> Repo.insert!()

      IO.puts("  ✅ Added #{mapping.source} mapping: #{mapping.value} → #{mapping.category_name}")
    end
  else
    IO.puts("  ⚠️  Category not found: #{mapping.category_name}")
  end
end

# Cross-classification mappings (generated by extraction logic)
cross_classification_mappings = [
  # Universal secondary mappings (English) - used by all sources
  %{source: "ticketmaster", type: nil, value: "arts", category_name: "Arts", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "nightlife", category_name: "Nightlife", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "festivals", category_name: "Festivals", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "festival", category_name: "Festivals", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "community", category_name: "Community", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "business", category_name: "Business", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "education", category_name: "Education", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "family", category_name: "Family", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "concerts", category_name: "Concerts", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "concert", category_name: "Concerts", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "performance", category_name: "Theatre", priority: 85, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "theatre", category_name: "Theatre", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "sports", category_name: "Sports", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "comedy", category_name: "Comedy", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "film", category_name: "Film", priority: 90, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "dance", category_name: "Arts", priority: 85, locale: "en"},
  %{source: "ticketmaster", type: nil, value: "exhibition", category_name: "Arts", priority: 85, locale: "en"},

  # Bandsintown secondary mappings
  %{source: "bandsintown", type: nil, value: "arts", category_name: "Arts", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "nightlife", category_name: "Nightlife", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "festivals", category_name: "Festivals", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "festival", category_name: "Festivals", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "community", category_name: "Community", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "business", category_name: "Business", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "education", category_name: "Education", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "family", category_name: "Family", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "concerts", category_name: "Concerts", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "concert", category_name: "Concerts", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "performance", category_name: "Theatre", priority: 85, locale: "en"},
  %{source: "bandsintown", type: nil, value: "theatre", category_name: "Theatre", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "sports", category_name: "Sports", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "comedy", category_name: "Comedy", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "film", category_name: "Film", priority: 90, locale: "en"},
  %{source: "bandsintown", type: nil, value: "dance", category_name: "Arts", priority: 85, locale: "en"},
  %{source: "bandsintown", type: nil, value: "exhibition", category_name: "Arts", priority: 85, locale: "en"},

  # Karnet secondary mappings (English)
  %{source: "karnet", type: nil, value: "arts", category_name: "Arts", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "nightlife", category_name: "Nightlife", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "festivals", category_name: "Festivals", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "festival", category_name: "Festivals", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "community", category_name: "Community", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "business", category_name: "Business", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "education", category_name: "Education", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "family", category_name: "Family", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "concerts", category_name: "Concerts", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "concert", category_name: "Concerts", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "performance", category_name: "Theatre", priority: 85, locale: "en"},
  %{source: "karnet", type: nil, value: "theatre", category_name: "Theatre", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "sports", category_name: "Sports", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "comedy", category_name: "Comedy", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "film", category_name: "Film", priority: 90, locale: "en"},
  %{source: "karnet", type: nil, value: "dance", category_name: "Arts", priority: 85, locale: "en"},
  %{source: "karnet", type: nil, value: "exhibition", category_name: "Arts", priority: 85, locale: "en"},

  # Karnet Polish mappings (from extraction logic)
  %{source: "karnet", type: nil, value: "koncerty", category_name: "Concerts", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "festiwale", category_name: "Festivals", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "spektakle", category_name: "Theatre", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "wystawy", category_name: "Arts", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "literatura", category_name: "Arts", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "inne", category_name: "Community", priority: 80, locale: "pl"},
  %{source: "karnet", type: nil, value: "w-gminach-metropolii", category_name: "Community", priority: 85, locale: "pl"},

  # Additional Polish terms from the extraction patterns
  %{source: "karnet", type: nil, value: "festiwal", category_name: "Festivals", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "koncert", category_name: "Concerts", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "wystawa", category_name: "Arts", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "spektakl", category_name: "Theatre", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "teatr", category_name: "Theatre", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "kino", category_name: "Film", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "opera", category_name: "Arts", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "balet", category_name: "Arts", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "taniec", category_name: "Arts", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "muzyka", category_name: "Concerts", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "jazz", category_name: "Concerts", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "rock", category_name: "Concerts", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "dzieci", category_name: "Family", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "dziecko", category_name: "Family", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "warsztaty", category_name: "Education", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "konferencja", category_name: "Business", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "spotkanie", category_name: "Community", priority: 90, locale: "pl"},
  %{source: "karnet", type: nil, value: "kabaret", category_name: "Comedy", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "komedia", category_name: "Comedy", priority: 100, locale: "pl"},
  %{source: "karnet", type: nil, value: "filmow", category_name: "Film", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "muzyczn", category_name: "Concerts", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "plener", category_name: "Community", priority: 90, locale: "pl"},
  %{source: "karnet", type: nil, value: "wernisaż", category_name: "Arts", priority: 95, locale: "pl"},
  %{source: "karnet", type: nil, value: "premiera", category_name: "Theatre", priority: 95, locale: "pl"}
]

# Insert all mappings
Enum.each(cross_classification_mappings, insert_mapping)

IO.puts("\n✅ Cross-classification mappings seeded successfully!")
IO.puts("   Added mappings for multi-category support")
IO.puts("   These enable the cross-classification logic in CategoryExtractor")