# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US

reviews:
  # Enable high-level summary for large PRs
  high_level_summary: true

  # Show review status
  review_status: true

  # Request changes workflow
  # Set to false so CodeRabbit comments don't block merging
  request_changes_workflow: false

  # Collapse walkthrough for cleaner view
  collapse_walkthrough: false

  # Review large PRs (don't skip based on size)
  auto_review:
    enabled: true

  # Path filters for what to review/ignore
  # Use ! prefix to exclude paths
  path_filters:
    - "lib/**/*.ex"
    - "lib/**/*.heex"
    - "test/**/*.exs"
    - "priv/repo/migrations/**/*.exs"
    - "!**/*.lock"
    - "!**/deps/**"
    - "!**/node_modules/**"
    - "!**/_build/**"
    - "!**/priv/static/assets/**"

  # Path-based review instructions
  path_instructions:
    - path: "lib/eventasaurus_discovery/sources/**"
      instructions: |
        Review scraper code for:
        - MetricsTracker integration (record_success/record_failure)
        - Proper external_id format: {source}_{type}_{id}_{date}
        - Job naming convention: {JobType}Job
        - Error category usage from ErrorCategories module

    - path: "lib/eventasaurus_web/live/admin/**"
      instructions: |
        Review admin pages for:
        - Use of shared HealthComponents
        - Consistent color system (:blue, :green, :yellow, :red, :purple)
        - Proper refresh handler implementation
        - Repo.replica() usage for read queries

    - path: "test/**"
      instructions: |
        Review tests for:
        - Proper async: true usage where appropriate
        - Meaningful assertions
        - Edge case coverage

chat:
  # Enable chat features
  auto_reply: true

# Tone and style
tone_instructions: |
  Be concise and actionable. Focus on:
  - Security vulnerabilities
  - Performance issues
  - Elixir/Phoenix best practices
  - Pattern consistency with existing codebase
