import Config

# Set environment
config :eventasaurus, :environment, :dev

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.

# Set development-specific Supabase configuration
# This overrides the main supabase.exs config for development
config :eventasaurus, :supabase,
  url: "http://127.0.0.1:54321",  # Local Supabase URL
  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0",  # Default anon key for local Supabase
  database_url: "postgresql://postgres:postgres@127.0.0.1:54322/postgres",  # Local DB - NOTE: PostgreSQL runs on port 54322
  auth: %{
    site_url: "http://localhost:4000",
    additional_redirect_urls: ["http://localhost:4000/auth/callback"],
    auto_confirm_email: true
  }

# Configure PostHog settings for development
config :eventasaurus, :posthog,
  api_key: System.get_env("POSTHOG_PUBLIC_API_KEY"),
  api_host: "https://eu.i.posthog.com"



config :eventasaurus, EventasaurusWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "OW51JE7b0kmI7NHAjS+859KMrYf+jrpHFa9xyMqmlvNYmquOpS83H7Ea7eR59DMA",
  # Explicitly set HTTP adapter to Cowboy
  adapter: Phoenix.Endpoint.Cowboy2Adapter,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:eventasaurus, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:eventasaurus, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :eventasaurus, EventasaurusWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/eventasaurus_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :eventasaurus, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Import database credentials from dev.secret.exs
import_config "dev.secret.exs"
