import Config

# Set environment
config :eventasaurus, :environment, :prod

# Development-only features (disabled in production)
config :eventasaurus, :dev_quick_login, false

# Enable CDN in production
config :eventasaurus, :cdn, enabled: true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :eventasaurus, EventasaurusWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Eventasaurus.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Sentry configuration moved to config/runtime.exs for better robustness

# Database and Supabase configuration moved to config/runtime.exs
# This ensures environment variables are available at runtime

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
